import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({cashMovement:vi.fn(),getSession:vi.fn(),error:vi.fn(),success:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{auth:{getSession:mocks.getSession}}}));
vi.mock('sonner',()=>({toast:{error:mocks.error,success:mocks.success}}));
import {CashMovementDialog} from '../modules/cash/Cash';
const tenantId='a7000000-0000-4000-8000-000000000001';const branchId='b7000000-0000-4000-8000-000000000001';
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async (_key: string, callback: ()=>unknown)=>callback()}});mocks.getSession.mockResolvedValue({data:{session:{access_token:'operator-token'}},error:null});window.electron={cashMovement:mocks.cashMovement} as any;});
it('recovers the original reference and exact payload after response loss and remount',async()=>{
 let total=0;const committed=new Set<string>();
 mocks.cashMovement.mockImplementation(async(args)=>{
  const reference=args._reference;
  if(committed.has(reference))return 'f7000000-0000-0000-0000-000000000001';
  committed.add(reference);total+=1001;
  if(committed.size===1)throw new Error('Response lost after commit');
  return {data:'f7000000-0000-0000-0000-000000000002',error:null};
 });
 render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'1.001'}});
 fireEvent.change(screen.getByPlaceholderText('e.g. Extra float'),{target:{value:'Extra float receipt'}});
 fireEvent.change(screen.getByLabelText('Movement reference'),{target:{value:'FLOAT-20260914-001'}});
 fireEvent.click(screen.getByRole('button',{name:'Record'}));await waitFor(()=>expect(mocks.error).toHaveBeenCalled());
 cleanup();render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 expect(screen.getByLabelText('Movement reference')).toHaveValue('FLOAT-20260914-001');
 fireEvent.click(screen.getByRole('button',{name:'Record'}));await waitFor(()=>expect(mocks.success).toHaveBeenCalled());
 expect(total).toBe(1001);expect(mocks.cashMovement.mock.calls[1]).toEqual(mocks.cashMovement.mock.calls[0]);
});
it('does not send cash mutations when draft persistence fails',async()=>{
 render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'1.001'}});
 fireEvent.change(screen.getByPlaceholderText('e.g. Extra float'),{target:{value:'Verified float'}});
 fireEvent.change(screen.getByLabelText('Movement reference'),{target:{value:'FLOAT-20260914-002'}});
 const write=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('Storage full');});
 fireEvent.click(screen.getByRole('button',{name:'Record'}));await waitFor(()=>expect(mocks.error).toHaveBeenCalled());
 expect(mocks.cashMovement).not.toHaveBeenCalled();write.mockRestore();
});
it('retains a confirmed receipt on remount and starts fresh only explicitly',async()=>{
 mocks.cashMovement.mockResolvedValue('f7000000-0000-0000-0000-000000000001');
 render(<CashMovementDialog open type="out" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'1.001'}});
 fireEvent.change(screen.getByPlaceholderText(/e.g. (Safe withdrawal|Supplier payment)/),{target:{value:'Safe deposit'}});
 fireEvent.change(screen.getByLabelText('Movement reference'),{target:{value:'SAFE-001'}});
 fireEvent.click(screen.getByRole('button',{name:'Record'}));await waitFor(()=>expect(mocks.success).toHaveBeenCalled());
 cleanup();render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000002" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 expect(screen.queryByRole('button',{name:'Record'})).not.toBeInTheDocument();
 expect(screen.getByLabelText('Movement reference')).toHaveValue('SAFE-001');
 fireEvent.click(screen.getByRole('button',{name:'Start another physical movement'}));
 await waitFor(()=>expect(screen.getByLabelText('Movement reference')).toHaveValue(''));
 expect(mocks.cashMovement).toHaveBeenCalledTimes(1);
});
it('recovers a pending movement after its original session has closed',async()=>{
 mocks.cashMovement.mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce('f7000000-0000-0000-0000-000000000001');
 render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'1.001'}});
 fireEvent.change(screen.getByPlaceholderText('e.g. Extra float'),{target:{value:'Verified float'}});
 fireEvent.change(screen.getByLabelText('Movement reference'),{target:{value:'FLOAT-CLOSED'}});
 fireEvent.click(screen.getByRole('button',{name:'Record'}));await waitFor(()=>expect(mocks.error).toHaveBeenCalled());
 cleanup();render(<CashMovementDialog open type="out" sessionId={null} actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 expect(screen.getByText(/earlier cash session/)).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Resolve cancellation'}));
 await waitFor(()=>expect(mocks.success).toHaveBeenCalledWith('Cash movement confirmed'));
 expect(mocks.cashMovement.mock.calls[1][2]).toBe(true);
 expect(mocks.cashMovement.mock.calls[1][0]).toEqual(mocks.cashMovement.mock.calls[0][0]);
 expect(screen.getByRole('status')).toHaveTextContent('recorded');
});
it('blocks corrupt recovery data without overwriting it',async()=>{
 const key='zaipos:cash-movement:v1:cashier';localStorage.setItem(key,'{damaged');
 localStorage.setItem('zaipos:cash-movement-draft:e7000000-0000-0000-0000-000000000001:in','{damaged');
 render(<CashMovementDialog open type="in" sessionId="e7000000-0000-0000-0000-000000000001" actorId="cashier" tenantId={tenantId} branchId={branchId} onClose={()=>undefined}/>);
 expect(screen.getByRole('alert')).toHaveTextContent('unreadable');
 expect(screen.getByRole('button',{name:'Record'})).toBeDisabled();
 expect(localStorage.getItem(key)).toBe('{damaged');expect(mocks.cashMovement).not.toHaveBeenCalled();
});
