-- Pricing operation rule_id may be generated by the operation itself and stored
-- only after completion. Replay identity is therefore governed by the immutable
-- request hash, operation kind and input product, not by the generated output rule.
BEGIN;

CREATE OR REPLACE FUNCTION public.claim_pricing_policy_operation_internal_v1(
  _tenant_id uuid,
  _operation_id text,
  _operation_kind text,
  _request_hash text,
  _actor_id uuid,
  _rule_id uuid,
  _product_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  _inserted integer;
  _existing public.pricing_policy_operations;
BEGIN
  INSERT INTO public.pricing_policy_operations(
    tenant_id, operation_id, operation_kind, request_hash,
    actor_id, rule_id, product_id
  ) VALUES (
    _tenant_id, _operation_id, _operation_kind, _request_hash,
    _actor_id, _rule_id, _product_id
  )
  ON CONFLICT (tenant_id, operation_id) DO NOTHING;
  GET DIAGNOSTICS _inserted = ROW_COUNT;

  IF _inserted = 1 THEN
    RETURN NULL;
  END IF;

  SELECT * INTO _existing
  FROM public.pricing_policy_operations
  WHERE tenant_id = _tenant_id AND operation_id = _operation_id
  FOR UPDATE;

  IF _existing.operation_kind <> _operation_kind
    OR _existing.request_hash <> _request_hash
    OR _existing.product_id IS DISTINCT FROM _product_id
  THEN
    RAISE EXCEPTION 'Pricing operation ID was already used with different input';
  END IF;
  IF _existing.completed_at IS NULL OR _existing.result IS NULL THEN
    RAISE EXCEPTION 'Pricing operation did not complete';
  END IF;
  RETURN _existing.result;
END
$$;

REVOKE ALL ON FUNCTION public.claim_pricing_policy_operation_internal_v1(uuid,text,text,text,uuid,uuid,uuid)
FROM PUBLIC, anon, authenticated;

COMMIT;
